### PR TITLE
replaces all SimpleJSONParser calls to ParseJSON

### PR DESCRIPTION
**Pull request by sudo97**
This is simple, but I saw a FIXME comment. Also left one new line in SimpleJSONParser() that just returns ParseJSON(), just in case.

### CODE REVIEW

**Comment by sudo97** [comment]
New GetStringFromUrl function

**Comment by sudo97** [comment]
I'm sorry, second commit was wrong

**Comment by adiffmike** [comment]
Just a heads up on this.

I don't have the bandwidth to test these commits  - and haven't touched this in years - but if there's a native parser now for JSON thats an obvious enhancement and the code changes look solid so I'm going to merge this and cross my fingers a bit....

**Comment by sudo97** [comment]
Is this project still being developed? Or is it freezed?

**Comment by adiffmike** [comment]
Its not being actively developed. I'll check in on it every so often if someone has a pull request etc. Its a bit long in the tooth at this point.

**Pull request merged**
